watch_stylesheet: true
watch_config: true
debug: false
update_check: true
bars:
    primary-bar:
        enabled: true
        screens: ["*"]
        class_name: "yasb-bar"
        alignment:
            position: "top"
            center: false
        animation:
            enabled: true
            duration: 400
        blur_effect:
            enabled: true
            acrylic: false
            dark_mode: true
            round_corners: true
            round_corners_type: "normal"
            border_color: "None"
        window_flags:
            always_on_top: false
            windows_app_bar: true
        dimensions:
            width: "100%"
            height: 32
        padding:
            top: 4
            left: 4
            bottom: 4
            right: 4
        widgets:
            left: ["komorebi_workspaces", "active_window", "apps"]
            center: ["timeWeather_grouper"]
            right: ["systray", "media", "tools_grouper"]
widgets:
    home:
        type: "yasb.home.HomeWidget"
        options:
            label: "<span>\ueb51</span>"
        menu_list:
            - { title: "User Home", path: "~" }
            - { title: "Downloads", path: "D:\\Downloads" }
            - { title: "Zen Downloads", path: "D:\\Zen Downloads" }
        system_menu: true
        power_menu: true
        blur: true
        border_color: "None"
        container_padding:
            top: 0
            left: 10
            bottom: 0
            right: 4
    komorebi_workspaces:
        type: "komorebi.workspaces.WorkspaceWidget"
        options:
            label_offline: "\u23fc Offline"
            label_workspace_btn: "\udb80\udd30"
            label_workspace_active_btn: "\udb80\udd2f"
            label_workspace_populated_btn: "\udb80\udd30"
            label_default_name: "{index}"
            label_zero_index: false
            hide_empty_workspaces: false
            hide_if_offline: true
            animation: false
    active_window:
        type: "yasb.active_window.ActiveWindowWidget"
        options:
            label: "{win[title]}"
            label_no_window: ""
            label_icon: true
            label_icon_size: 16
            max_length: 36
            max_length_ellipsis: "..."
            monitor_exclusive: false
    clock:
        type: "yasb.clock.ClockWidget"
        options:
            label: "{%a %b %d %H:%M}"
            label_alt: "{%A, %d %B %Y %H:%M}"
            timezones: []
            calendar:
                blur: true
                round_corners: true
                round_corners_type: "normal"
                border_color: "None"
                alignment: "center"
                direction: "down"
            callbacks:
                on_left: "toggle_calendar"
                on_right: "toggle_label"
    apps:
        type: "yasb.applications.ApplicationsWidget"
        options:
            container_padding:
                top: 0
                left: 8
                bottom: 0
                right: 8
            label: "{data}"
            image_icon_size: 20
            app_list:
                - {
                      icon: "C:\\Users\\ADITYA\\.config\\yasb\\icons\\zen.svg",
                      launch: "C:\\Program Files\\Zen Browser\\zen.exe",
                  }
                - {
                      icon: "C:\\Users\\ADITYA\\.config\\yasb\\icons\\vscode.svg",
                      launch: "D:\\Microsoft VS Code\\Code.exe",
                  }
                - {
                      icon: "C:\\Users\\ADITYA\\.config\\yasb\\icons\\powershell.ico",
                      launch: "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
                  }
                - {
                      icon: "C:\\Users\\ADITYA\\.config\\yasb\\icons\\obsidian.svg",
                      launch: "D:\\Softwares\\Obsidian\\Obsidian.exe",
                  }
    taskbar:
        type: "yasb.taskbar.TaskbarWidget"
        options:
            tooltip: true
            animation:
                enabled: true
                duration: 200
                type: "fadeInOut"
            icon_size: 16
            ignore_apps:
                processes: []
                titles: []
                classes: []
            container_padding:
                top: 0
                left: 0
                bottom: 0
                right: 0
    systray:
        type: "yasb.systray.SystrayWidget"
        options:
            class_name: "systray"
            label_collapsed: "\uf47d"
            label_expanded: "\uf460"
            label_position: "right"
            icon_size: 16
            pin_click_modifier: "alt"
            show_unpinned: false
            show_unpinned_button: true
            show_battery: false
            show_volume: false
            show_network: false
            tooltip: true
    weather:
        type: "yasb.weather.WeatherWidget"
        options:
            label: "<span>{icon}</span> {temp}"
            label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
            api_key: "4ddd5c665b9d48c781b150325250408"
            location: "kolkata"
            show_alerts: true
            update_interval: 600
            hide_decimal: true
            units: "metric"
            icons:
                sunnyDay: "\ue30d"
                clearNight: "\ue32b"
                cloudyDay: "\ue312"
                cloudyNight: "\ue311"
                rainyDay: "\ue308"
                rainyNight: "\ue333"
                snowyIcyDay: "\ue30a"
                snowyIcyNight: "\ue335"
                blizzardDay: "\udb83\udf36"
                blizzardNight: "\udb83\udf36"
                foggyDay: "\ue303"
                foggyNight: "\ue346"
                thunderstormDay: "\ue30f"
                thunderstormNight: "\ue338"
                default: "\uebaa"
            callbacks:
                on_left: "toggle_card"
                on_middle: "do_nothing"
                on_right: "toggle_label"
            weather_card:
                blur: true
                round_corners: true
                round_corners_type: "normal"
                border_color: "None"
                alignment: "right"
                direction: "down"
                icon_size: 64
                show_hourly_forecast: true
                time_format: "24h"
                hourly_point_spacing: 76
                hourly_icon_size: 32
                icon_smoothing: true
                temp_line_width: 2
                current_line_color: "#8EAEE8"
                current_line_width: 2
                current_line_style: "dot"
    media:
        type: "yasb.media.MediaWidget"
        options:
            label: "{title} - {artist}"
            label_alt: "{title}"
            hide_empty: true
            callbacks:
                on_left: "toggle_media_menu"
                on_middle: "toggle_play_pause"
                on_right: "toggle_label"
            max_field_size:
                label: 20
                label_alt: 16
            show_thumbnail: true
            controls_only: false
            controls_left: false
            controls_hide: true
            thumbnail_edge_fade: true
            thumbnail_padding: 32
            scrolling_label:
                enabled: false
            icons:
                prev_track: "\ue892"
                next_track: "\ue893"
                play: "\ue768"
                pause: "\ue769"
            media_menu:
                blur: true
                round_corners: true
                round_corners_type: "normal"
                border_color: "None"
                alignment: "right"
                direction: "down"
                offset_top: 6
                offset_left: 0
                thumbnail_corner_radius: 4
                thumbnail_size: 80
                max_title_size: 60
                max_artist_size: 20
                show_source: true
            media_menu_icons:
                play: "\ue768"
                pause: "\ue769"
                prev_track: "\ue892"
                next_track: "\ue893"
    volume:
        type: "yasb.volume.VolumeWidget"
        options:
            label: "<span>{icon}</span> {level}"
            label_alt: "{volume}"
            volume_icons:
                - "\ueee8"
                - "\uf026"
                - "\uf027"
                - "\uf027"
                - "\uf028"
            callbacks:
                on_right: "exec cmd.exe /c start ms-settings:sound"
    notifications:
        type: "yasb.notifications.NotificationsWidget"
        options:
            label: "<span>\uf476</span> {count}"
            label_alt: "{count} notifications"
            hide_empty: true
            tooltip: false
            callbacks:
                on_left: "toggle_notification"
                on_right: "do_nothing"
                on_middle: "toggle_label"
            container_padding:
                top: 0
                left: 4
                bottom: 0
                right: 4
    power_menu:
        type: "yasb.power_menu.PowerMenuWidget"
        options:
            label: "\uf011"
            uptime: true
            blur: false
            blur_background: true
            animation_duration: 200
            button_row: 3
            buttons:
                shutdown: ["\uf011", "Shut Down"]
                restart: ["\uead2", "Restart"]
                signout: ["\udb80\udf43", "Sign out"]
                hibernate: ["\uf28e", "Hibernate"]
                sleep: ["\u23fe", "Sleep"]
                cancel: ["\ueab8", "Close"]
            container_padding:
                top: 0
                left: 0
                bottom: 0
                right: 0
    bluetooth:
        type: "yasb.bluetooth.BluetoothWidget"
        options:
            label: "<span>{icon}</span>"
            label_alt: "{device_name}"
            icons:
                bluetooth_on: "\udb80\udcaf"
                bluetooth_off: "\udb80\udcb2"
                bluetooth_connected: "\udb80\udcb1"
            callbacks:
                on_right: "exec cmd.exe /c start ms-settings:bluetooth"
    timeWeather_grouper:
        type: "yasb.grouper.GrouperWidget"
        options:
            class_name: "grouped-widgets"
            widgets: ["clock", "weather"]
            container_padding:
                top: 0
                left: 2
                bottom: 0
                right: 6
    tools_grouper:
        type: "yasb.grouper.GrouperWidget"
        options:
            class_name: "grouped-widgets"
            widgets:
                ["volume", "bluetooth", "notifications", "home", "power_menu"]
            container_padding:
                top: 0
                left: 2
                bottom: 0
                right: 6
